@startuml
class Cliente {
    - id: PK
    - nombre: String
    - apellido
    - email 
}

class Empresa {
    - id
    - razon_social
    - email
}

class Equipo {
    - id
    - nombre
    - escudo
    - pais 
}

class Apuesta {
    - id 
    - monto
    - monto_minimo
}

class Partido {
    - id
    - fecha 
    - equipo_local
    - equipo_visitante
}

Equipo --* Partido: equipo local
Equipo --* Partido: equipo visitante

Cliente --> Apuesta: realiza apuesta

Cliente --|> Model
Empresa --|> Model
Partido --|> Model
Equipo --|> Model

Apuesta --> Partido: se realiza sobre


@enduml