@startuml
class Cliente {
    - id: PK
    - nombre: String
    - apellido
    - email 
    - activado: Boolean
    - apuestas
}

class Empresa {
    - id
    - razon_social
    - email
    - activado: Boolean
}

class Equipo {
    - id
    - nombre
    - escudo
    - pais 
    - puntaje 
    - apuestas
    - activado: Boolean
}

class Apuesta {
    - id 
    - monto
    - fecha
    - equipo_ganador_id
    - partido_id
    - cliente_id
    - ganancia 
}

class Partido {
    - id
    - fecha 
    - equipo_local
    - equipo_visitante
    - finalizado 
    - equipo_ganador_id
}

Equipo --* Partido: equipo local
Equipo --* Partido: equipo visitante

Cliente --> Apuesta: realiza apuesta

Cliente --|> Model
Empresa --|> Model
Partido --|> Model
Equipo --|> Model

Apuesta --> Partido: se realiza sobre


@enduml

