@startuml

actor Cliente
boundary ApuestaController
participant PartidoSchema
participant ApuestaSchema
participant PartidoModel
participant ApuestaModel
database data

Cliente -> ApuestaController: GET all
activate ApuestaController
ApuestaController -> PartidoModel: get all partidos finalizados
activate PartidoModel
PartidoModel -> data: select all
PartidoModel <- data: registros partidos finalizados
PartidoSchema <- PartidoModel: dump many=True
deactivate PartidoModel
activate PartidoSchema
PartidoSchema -> ApuestaController: collection Json
deactivate PartidoSchema
Cliente <- ApuestaController: Json
deactivate ApuestaController

Cliente -> ApuestaController: POST
activate ApuestaController
ApuestaController -> ApuestaModel: guardar apuesta
activate ApuestaModel
ApuestaModel -> data: Insert
ApuestaModel <- data: Object
ApuestaSchema <- ApuestaModel: Dump Object
deactivate ApuestaModel
activate ApuestaSchema
ApuestaSchema -> ApuestaController: Json
deactivate ApuestaSchema
Cliente -> ApuestaController: Json
deactivate ApuestaController

@enduml
