from .clientes import Cliente as ClienteController
from .clientes import Clientes as ClientesController
from .partidos import Partido as PartidoController
from .partidos import Partidos as PartidosController
from .equipos import Equipo as EquipoController
from .equipos import Equipos as EquiposController
from .empresas import Empresa as EmpresaController
from .empresas import Empresas as EmpresasController
from .apuesta import Apuesta as ApuestaController
from .apuesta import Apuestas as ApuestasController
from .cuota import Cuota as CuotaController
from .cuota import Cuotas as CuotasController
from .apuesta import ApuestasGanadas as ApuestasGanadasController
from .apuesta import ApuestaGanada as ApuestaGanadaController